apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "rocketchatcf.fullname" . }}
  labels:
    app: {{ template "rocketchatcf.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "rocketchatcf.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ template "rocketchatcf.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: DEPLOY_PLATFORM
          value: helm-chart
        - name: ADMIN_USERNAME
          value: admin
        - name: ADMIN_PASS
          value: admin
        - name: ADMIN_EMAIL
          value: admin@asdasdasdas.com
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MONGO_URL
        {{ if .Values.mongodb.mongodbUsername }}
          valueFrom:
            secretKeyRef:
              name: {{ template "rocketchatcf.fullname" . }}
              key: mongo-uri
        {{ else }}
          value: mongodb://{{ template "rocketchatcf.mongodb.fullname" . }}:27017/rocketchatcf
        {{ end }}
        {{ if .Values.host }}
        - name: ROOT_URL
          value: https://{{ .Values.host }}
        {{ end }}
        - name: MAIL_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "rocketchatcf.fullname" . }}
              key: mail-url
        {{- range $key, $value :=  .Values.config }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: rocket-data
          mountPath: /app/uploads
      volumes:
      - name: rocket-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "rocketchatcf.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}

