{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "rocketchatcf.fullname" . }}
  labels:
    app: {{ template "rocketchatcf.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- if .Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
{{- end }}
{{- if .Values.ingress.htpasswdString }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.ingress.authSecretName }}
    nginx.ingress.kubernetes.io/auth-realm: "Authenticate"
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.host }}
{{- if (ne "-" .Values.ingress.secretName) }}
    secretName: {{ .Values.ingress.secretName | default (printf "%s-tls" (include "rocketchatcf.fullname" .)) }}
{{- end }}
{{- end }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /{{ $.Release.Name }}
        backend:
          serviceName: {{ template "rocketchatcf.fullname" . }}
          servicePort: 3000
{{- end -}}
