apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.ingress.authSecretName }}
  labels:
    app: {{ template "rocketchatcf.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Name }}"
    release: "{{ .Release.Service }}"
  {{- if .Values.keepSecrets }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  auth: {{ .Values.ingress.htpasswdString | b64enc | quote }}