apiVersion: v1
kind: Service
metadata:
  name: {{ template "rocketchatcf.fullname" . }}
  labels:
    app: {{ template "rocketchatcf.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: {{ template "rocketchatcf.name" . }}
    release: "{{ .Release.Name }}"
